# Generated by Django 3.1.4 on 2022-01-11 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_auto_20220110_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='traveller',
            new_name='traveler',
        ),
    ]
